package config

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// validSandboxKeyRE restricts sandbox keys to characters safe for Lua table
// keys. Nested keys use dot notation (ZombieConfig.PopulationMultiplier).
var validSandboxKeyRE = regexp.MustCompile(`^[A-Za-z0-9_.]+$`)

func validSandboxKey(k string) bool {
	return validSandboxKeyRE.MatchString(k)
}

// validLuaValue reports whether a sandbox value contains no control
// characters. Values are written into SandboxVars.lua, which the server
// executes; anything else would allow Lua injection.
func validLuaValue(v string) bool {
	for _, r := range v {
		if r < 0x20 || r == 0x7f {
			return false
		}
	}
	return true
}

// luaValue renders a sandbox value as valid Lua: booleans and numbers stay
// raw, everything else is quoted as a string (escaping quotes/backslashes).
// Pre-quoted values pass through unchanged.
func luaValue(v string) string {
	v = strings.TrimSpace(v)
	if v == "true" || v == "false" {
		return v
	}
	if luaNumRE.MatchString(v) {
		return v
	}
	if len(v) >= 2 && ((v[0] == '"' && v[len(v)-1] == '"') || (v[0] == '\'' && v[len(v)-1] == '\'')) {
		return v
	}
	escaped := strings.ReplaceAll(v, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	return `"` + escaped + `"`
}

var luaNumRE = regexp.MustCompile(`^[+-]?([0-9]+\.?[0-9]*|\.[0-9]+)$`)

// WriteSandboxVars writes the generated SandboxVars.lua for this server.
func (c *ServerConfig) WriteSandboxVars() error {
	dir := filepath.Dir(c.SandboxVarsPath())
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating sandbox vars directory: %w", err)
	}

	// Defaults mirror the game's b42 "Apocalypse" preset
	// (server-files/media/lua/shared/Sandbox/Apocalypse.lua).
	vars := map[string]string{
		"Zombies":             "4",
		"Distribution":        "1",
		"DayLength":           "4",
		"StartYear":           "1",
		"StartMonth":          "7",
		"StartDay":            "9",
		"StartTime":           "2",
		"WaterShutModifier":   "14",
		"ElecShutModifier":    "14",
		"WaterShut":           "2",
		"ElecShut":            "2",
		"FoodLootNew":         "0.8",
		"WeaponLootNew":       "0.6",
		"OtherLootNew":        "0.8",
		"Temperature":         "3",
		"Rain":                "3",
		"ErosionSpeed":        "4",
		"ErosionDays":         "0",
		"Farming":             "3",
		"CompostTime":         "2",
		"StatsDecrease":       "3",
		"NatureAbundance":     "3",
		"Alarm":               "4",
		"LockedHouses":        "6",
		"GeneratorSpawning":   "4",
		"SurvivorHouseChance": "3",
		"VehicleStoryChance":  "3",
		"ZoneStoryChance":     "3",
		"AnnotatedMapChance":  "4",
		"TimeSinceApo":        "1",
		"NightDarkness":       "3",
		"Helicopter":          "2",
		"MetaEvent":           "2",
		"SleepingEvent":       "1",
		"ZombieLore":          zombieLoreBlock(nil),
	}

	// SANDBOX_MODE applies gameplay/performance presets on top of the base
	// Apocalypse values. SANDBOX_* env overrides below always win over them.
	for k, v := range sandboxModeOverrides(c.SandboxMode) {
		vars[k] = v
	}

	// SANDBOX_* env overrides may use Build 41 sandbox names, which b42
	// silently drops. Map the known renames to their b42 equivalents so
	// overrides keep working.
	legacyAliases := map[string]string{
		"FoodLoot":       "FoodLootNew",
		"WeaponLoot":     "WeaponLootNew",
		"OtherLoot":      "OtherLootNew",
		"SurvivorHouses": "SurvivorHouseChance",
		"MonthsSinceApo": "TimeSinceApo",
		"DarknessNight":  "NightDarkness",
	}

	nested := map[string]map[string]string{}
	for k, v := range c.SandboxVars {
		if !validSandboxKey(k) {
			fmt.Printf("WARNING: SANDBOX_%s: invalid key, ignoring (allowed: letters, digits, '_', '.')\n", k)
			continue
		}
		if !validLuaValue(v) {
			fmt.Printf("WARNING: SANDBOX_%s: value contains control characters, ignoring\n", k)
			continue
		}
		if alias, ok := legacyAliases[k]; ok {
			fmt.Printf("WARNING: SANDBOX_%s was renamed in b42, applying it to %s\n", k, alias)
			vars[alias] = luaValue(v)
			continue
		}
		// Nested keys use dot notation: SANDBOX_Map.AllowMiniMap=true
		// writes into the Map = { ... } table.
		section, sub, ok := strings.Cut(k, ".")
		if ok {
			if nested[section] == nil {
				nested[section] = map[string]string{}
			}
			nested[section][sub] = luaValue(v)
			continue
		}
		vars[k] = luaValue(v)
	}

	// Render the nested tables last so SANDBOX_MODE presets and SANDBOX_*
	// overrides both land in the final blocks (env overrides win).
	vars["ZombieConfig"] = zombieConfigBlock(c.SandboxMode, nested["ZombieConfig"])
	vars["ZombieLore"] = zombieLoreBlock(nested["ZombieLore"])
	for section, overrides := range nested {
		if section != "ZombieConfig" && section != "ZombieLore" {
			vars[section] = renderBlock(overrides)
		}
	}

	var sb strings.Builder
	sb.WriteString("-- Generated by project-zomboid-server-docker\n")
	sb.WriteString("SandboxVars = {\n")

	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for i, k := range keys {
		sep := ","
		if i == len(keys)-1 {
			sep = ""
		}
		v := vars[k]
		sb.WriteString(fmt.Sprintf("    %s = %s%s\n", k, v, sep))
	}

	sb.WriteString("}\n")

	return os.WriteFile(c.SandboxVarsPath(), []byte(sb.String()), 0644)
}

// sandboxModes are the accepted SANDBOX_MODE values, used for validation.
var sandboxModes = map[string]bool{
	"apocalypse":  true,
	"performance": true,
	"max":         true,
}

// sandboxModeOverrides returns the extra sandbox options a SANDBOX_MODE
// applies over the b42 Apocalypse base. Empty for the default mode.
func sandboxModeOverrides(mode string) map[string]string {
	switch mode {
	case "performance", "max":
		// World-cleanup knobs with near-zero gameplay impact. Corpses,
		// blood splats and rotten food pile up on long-running servers
		// and are well-known lag sources; the Apocalypse defaults never
		// remove them (or wait 9 days for corpses).
		return map[string]string{
			"HoursForCorpseRemoval":    "48",
			"BloodSplatLifespanDays":   "7",
			"DaysForRottenFoodRemoval": "14",
			"MaximumRatIndex":          "0",
			"HoursForWorldItemRemoval": "12",
		}
	default:
		return nil
	}
}

// zombieConfigBlock renders the b42 ZombieConfig table for the given
// SANDBOX_MODE plus any SANDBOX_ZombieConfig.* env overrides. The "max" mode
// cuts population pressure, which is the dominant factor for server TPS on
// long-running worlds.
func zombieConfigBlock(mode string, overrides map[string]string) string {
	zc := map[string]string{
		"PopulationMultiplier":      "0.65",
		"PopulationStartMultiplier": "1.0",
		"PopulationPeakMultiplier":  "1.5",
		"PopulationPeakDay":         "28",
		"RespawnHours":              "0.0",
		"RespawnUnseenHours":        "0.0",
		"RespawnMultiplier":         "0.0",
		"RedistributeHours":         "12.0",
		"FollowSoundDistance":       "100",
		"RallyGroupSize":            "20",
		"RallyGroupSizeVariance":    "50",
		"RallyTravelDistance":       "20",
		"RallyGroupSeparation":      "15",
		"RallyGroupRadius":          "3",
		"ZombiesCountBeforeDelete":  "300",
	}
	if mode == "max" {
		zc["PopulationMultiplier"] = "0.35"
		zc["PopulationStartMultiplier"] = "0.5"
		zc["PopulationPeakMultiplier"] = "1.0"
		zc["RedistributeHours"] = "24.0"
		zc["FollowSoundDistance"] = "50"
		zc["RallyGroupSize"] = "10"
		zc["RallyGroupSizeVariance"] = "25"
	}
	applyOverrides(zc, overrides)
	return renderBlock(zc)
}

// zombieLoreBlock renders the b42 ZombieLore table (Apocalypse values) plus
// any SANDBOX_ZombieLore.* env overrides.
func zombieLoreBlock(overrides map[string]string) string {
	zl := map[string]string{
		"Speed":                    "4",
		"SprinterPercentage":       "0",
		"Strength":                 "2",
		"Toughness":                "4",
		"Transmission":             "1",
		"Mortality":                "5",
		"Reanimate":                "3",
		"Cognition":                "3",
		"DoorOpeningPercentage":    "0",
		"CrawlUnderVehicle":        "5",
		"Memory":                   "2",
		"Sight":                    "5",
		"Hearing":                  "5",
		"SpottedLogic":             "true",
		"ThumpNoChasing":           "false",
		"ThumpOnConstruction":      "true",
		"ActiveOnly":               "1",
		"TriggerHouseAlarm":        "true",
		"ZombiesDragDown":          "true",
		"ZombiesCrawlersDragDown":  "false",
		"ZombiesFenceLunge":        "true",
		"ZombiesArmorFactor":       "2.0",
		"ZombiesMaxDefense":        "85",
		"ChanceOfAttachedWeapon":   "6",
		"ZombiesFallDamage":        "1.0",
		"DisableFakeDead":          "1",
		"PlayerSpawnZombieRemoval": "1",
	}
	applyOverrides(zl, overrides)
	return renderBlock(zl)
}

func applyOverrides(base, overrides map[string]string) {
	for k, v := range overrides {
		base[k] = v
	}
}

func renderBlock(entries map[string]string) string {
	keys := make([]string, 0, len(entries))
	for k := range entries {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("{\n")
	for i, k := range keys {
		sep := ","
		if i == len(keys)-1 {
			sep = ""
		}
		sb.WriteString(fmt.Sprintf("            %s = %s%s\n", k, entries[k], sep))
	}
	sb.WriteString("        }")
	return sb.String()
}
